### ISSUE TITLE
dwave/optimization/libdwave-optimization.so is missing in the plist produced by the '--record {plist}' directive

### ISSUE THREAD

**Issue by yurivict** [dwavesystems/dwave-optimization#59] opened 2024-07-15 06:33 UTC
'--record {plist}' should normally produce a correct plist, but dwave/optimization/libdwave-optimization.so is missing from plist.

Version: 0.1.0
Python-3.11
FreeBSD 14.1

**Comment by arcondello** [comment] 2024-07-15 14:50
It would be helpful to provide more context. I believe you're referring to 
```
python setup.py --record=plist.txt
```
as in  https://github.com/sfepy/sfepy/issues/455 ?

We unfortunately do not support `distutils` as it is deprecated. It looks like `setuptools` does not support `--record`
```
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --record not recognized
```

**Comment by yurivict** [comment] 2024-07-15 15:46
> We unfortunately do not support distutils as it is deprecated.

I see. pyproject.toml works fine.

Maybe you can consider to remove setup.py?

**Comment by arcondello** [comment] 2024-07-15 15:52
> Maybe you can consider to remove setup.py?

`setup.py` is also, confusingly, used by `setuptools`. See [should setup.py be deleted](https://packaging.python.org/en/latest/guides/modernize-setup-py-project/). We need `setup.py` to handle dynamic metadata and build configuration.

> The plist is still wrong when pyproject.toml is used.

I don't think the issue is in this package, most likely it is something in `setuptools` and/or [setuptools_dso](https://mdavidsaver.github.io/setuptools_dso/usage.html).

**Comment by yurivict** [comment] 2024-07-15 15:55
[Here](https://freebsd.org/~yuri/dwave-optimization-0.1.0-build.log) is a complete build log.

The plist file /usr/ports/science/py-dwave-optimization/work-py311/.PLIST.mktmp generated in the process still has missing files.

**Comment by arcondello** [comment] 2024-07-15 16:03
So I can confirm that `dwave/optimization/libdwave-optimization.so` shows up in the `RECORD` of the [wheels on pypi](https://pypi.org/project/dwave-optimization/0.1.0/#files).

I also see in your build log that the file is being correctly created and added
```
...
adding 'dwave/optimization/generators.py'
adding 'dwave/optimization/libdwave-optimization.so'
adding 'dwave/optimization/mathematical.py'
...
```
so I am not sure why it wouldn't show up in the `RECORD`  here:
```
/usr/local/bin/python3.11 -B /usr/ports/Mk/Scripts/strip_RECORD.py  /usr/ports/science/py-dwave-optimization/work-py311/stage/usr/local/lib/python3.11/site-packages/dwave_optimization-0.1.0*.dist-info/RECORD >> /usr/ports/science/py-dwave-optimization/work-py311/.PLIST.pymodtmp ...
```

Which looks like where you build the PLIST from?

**Comment by yurivict** [comment] 2024-07-15 16:07
> Which looks like where you build the PLIST from?

Yes, this file is the source of plist.

This is done in the FreeBSD ports framework.

For virtually all other (several thousands) python-based packages plist is built correctly, but dwave-oprimization has some bug.

**Comment by arcondello** [comment] 2024-07-15 16:08
Can you provide the `RECORD` file from that build script here?

**Comment by yurivict** [comment] 2024-07-15 16:24
I apologize, pyproject.toml in fact produces the correct plist.
(My bad, I didn't look properly the previous time.)

So maybe you can just remove setup.py since distutils is deprecated?

**Comment by arcondello** [comment] 2024-07-15 16:31
> So maybe you can just remove setup.py since distutils is deprecated?

See [above]( https://github.com/dwavesystems/dwave-optimization/issues/59#issuecomment-2228838272)

>  setup.py is also, confusingly, used by setuptools. See [should setup.py be deleted](https://packaging.python.org/en/latest/guides/modernize-setup-py-project/). We need setup.py to handle dynamic metadata and build configuration.

**Comment by arcondello** [comment] 2024-07-15 16:36
Sounds like this is resolved, so closing this issue for now.

**Closed by arcondello** 2024-07-15 16:36 UTC
Labels: bug
